### ISSUE TITLE
Mono Runtime support

### ISSUE THREAD

**Issue by a1e3cdc47c9eae132bd41ae1f5d0510d** [MineLib/MineLib.Network#3]
A "System.Security.Cryptography.CryptographicException: Store Root doesn't exists." is thrown when I try to connect to my server. I imported root certs using mozroots but it didn't help...
See http://www.mono-project.com/docs/faq/security/ for fixes. I would implement a ICertificatePolicy class.

**Comment by Aragas** [comment]
Hm. Hard to say why. Try this - https://github.com/Aragas/MineLib.Network/tree/MonoFix

**Comment by a1e3cdc47c9eae132bd41ae1f5d0510d** [comment]
doesn't work... but i also dont know why, there is no cert. i think its an issue with bouncycastle.crypro

**Comment by a1e3cdc47c9eae132bd41ae1f5d0510d** [comment]
it crashes the first time on line 66 in Yggdrasil.cs

**Comment by Aragas** [comment]
Try last commit

**Comment by a1e3cdc47c9eae132bd41ae1f5d0510d** [comment]
still failing

**Comment by Aragas** [comment]
Dunno, maybe there is an error in mono detection. Try again last commit

**Comment by a1e3cdc47c9eae132bd41ae1f5d0510d** [comment]
no thats not a error in mono detection... i will try last commit in about 10 min, i will now test if it works if i go with offline mode

**Comment by a1e3cdc47c9eae132bd41ae1f5d0510d** [comment]
ok more or less good news:
generating own response with:
                        login = new Yggdrasil.Response();
            login.AccessToken = "OFFLINE";
            login.ClientToken = "OFFLINE";
            login.Profile = new Yggdrasil.SelectedProfile();
            login.Profile.ID = "OFFLINE";
            login.Profile.Name = "Castelbuilder123";
worked! Just a error came that the server stopped the handshake (because of online-mode=true).

So its just Yggdrasil

**Comment by Aragas** [comment]
Happens. So, i guess, everything works.

**Comment by a1e3cdc47c9eae132bd41ae1f5d0510d** [comment]
but it wont connect to the mojang servers
EDIT: i will do a restart, maybe a restart is required for certs changes to take effect

**Comment by Aragas** [comment]
Ah, you mean, offline works. It's strange. I'll search for some info, but won't promise anything.

**Comment by a1e3cdc47c9eae132bd41ae1f5d0510d** [comment]
found the issue
you don't hook the cert validating method. i will code a bit and then send a push request

**Comment by a1e3cdc47c9eae132bd41ae1f5d0510d** [comment]
ok that was a crazy bug of my computer + mono

run at the start of yggdrasil.login the following command:
certmgr -ssl https://authserver.mojang.com/authenticate

ALSO: the command must be run in a console visible to the user, the user must confirm the adding of certs
